# Generated by Django 4.2.7 on 2023-11-19 01:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Pancard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=20, null=True)),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("confidence", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("W", "Waiting"),
                            ("P", "Processing"),
                            ("C", "Completed"),
                        ],
                        default="W",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        blank=True,
                        choices=[("T", "Tampered"), ("O", "Original")],
                        default="T",
                        max_length=1,
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "get_latest_by": ["datetime"],
            },
        ),
        migrations.CreateModel(
            name="PancardImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="service/images")),
                ("datetime", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "pancard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="service.pancard",
                    ),
                ),
            ],
            options={
                "get_latest_by": ["datetime"],
            },
        ),
        migrations.CreateModel(
            name="PanIntermediate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="service/generated")),
                (
                    "panimg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="service.pancardimage",
                    ),
                ),
            ],
        ),
    ]
