# Generated by Django 4.2.7 on 2023-11-19 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="panintermediate",
            name="panimg",
        ),
        migrations.AddField(
            model_name="pancardimage",
            name="diff",
            field=models.ImageField(blank=True, null=True, upload_to="service/images"),
        ),
        migrations.AddField(
            model_name="pancardimage",
            name="thresh",
            field=models.ImageField(blank=True, null=True, upload_to="service/images"),
        ),
        migrations.DeleteModel(
            name="PanIntermediate",
        ),
    ]
