# Generated by Django 4.2.7 on 2023-11-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0002_remove_panintermediate_panimg_delete_panoriginal_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PanOriginal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="service/images")),
            ],
        ),
    ]
